language: node_js
node_js:
- "10"
before_script:
- npm install -g jsdoc
- npm install
script: jsdoc -c jsdoc.conf.json src/
notifications:
  webhooks: https://chat.citizenscience.ch/hooks/xnYY4LLB2LWXqmxHd/ABijvSTDjRoNvPLin6JyLTRyBDGNQTDmihLutzRcT5bDHmWg
deploy:
  provider: pages
  skip_cleanup: true
  allow_empty_commit: true
  commiter-from-gh: true
  keep_history: false
  github_token: $GH_TOKEN
  local_dir: docs
  
